---
title: "The Layers of a Computer System"
---

To fully understand computer architecture, it is important to understand
the idea of abstraction as it is used in the field of computer science.
**Abstraction** is an idea of dealing with complex and interconnected
systems whereby a user is only interested in the operations of a certain
level of complexity and suppresses more complex details. 

Abstraction is analogous to looking at Google map of a large country, such as the USA.
We can see the individual states, large lakes, surrounding oceans, and
neighboring countries. At this level of abstraction, one is unable to
see the finer details within a state (such as the names of cities,
towns, and major roads). However, zooming in provides an increased level
of detail.  The entire country is no longer visible; instead, perhaps
only a single state (e.g., Louisiana) and its neighbors are visible. At
this *zoomed in* level, we can now see some of the cities and major roads.
However, we cannot see some of the details of the *zoomed out* level such
as the states that are not immediate neighbors or the oceans. If we *zoom
in* to an even lower level, we can see street names, major buildings, and
so on. Again, we lose some of the details at the higher levels. Dividing
a complex system (like a map) into levels that progressively abstract
away detail allows users of the system to only deal with information
that is relevant at a given time.

![The multiple layers of a
computer](images/Lesson05-01.png){#fig-complayers}


A computer is a very complex system consisting of multiple layers (see
@fig-complayers). At the very top is the **user**. Users interact with
computers in a variety of ways. That is, they can (and do) interact
directly with applications (like a spreadsheet application, a game, or a
Web browser). Users can also interact directly with the operating system
(e.g., through its GUI or via the console) and with system utilities
(think of applications that are provided by the operating system). 


The **application layer** is the next layer, immediately below the user. It
is the layer that a computer user typically interacts with. For example,
a user can type and send an email without needing to know how the
characters on the screen are made to appear on another computer perhaps
one thousand miles away. A user might double-click an audio file on the
desktop without needing to know how the computer understands what a
double-click is or how to “play” the audio file.

The next layer is the **operating system** layer. This layer understands
user inputs (like typing or double- clicks) and figures out ways of
interpreting and executing those inputs. There are many examples of
operating systems (e.g., Linux, Windows, MacOS, Unix, Solaris). Of
these, Window is still the most common. What is the operating system on
your Raspberry Pi? At its core, the operating system is what allows
users to interact with the computer and actually make use of it.

**System utilities** are like applications, but provided directly by the
operating system. In one sense, they provide an interface to certain
parts of the operating system that allow users to do frequently needed
things. For example, the system utility of copying or moving files is
often used. Users don't have to install an application that permits
copying and moving files around. This is a system utility provided by
the operating system. Since system utilities are essentially embedded in
the operating system, this layer sits at the same level as the operating
system layer.

The layer beneath the operating system layer is the **hardware
abstraction** layer (or HAL). Sometimes, this layer is referred to as
the device driver layer. There are many different types and designs of
computers, and this layer makes sure that the computer hardware acts the
same regardless of the computer's design. For example, it makes sure
that the “on” button switches on the computer regardless of where it is
located. It makes sure that hitting a specific button opens the CD
drive. It provides the operating system with clear instructions on how
it can interact with the physical hardware of the computer.

The bottom layer is the **hardware layer**. It represents the physical,
tangible stuff that you can see or touch (e.g., keyboard, monitor,
mouse, case, power supply, motherboard, etc).
