---
title: "Bubble Sort"
---

The bubble sort processes a list of items from left-to-right. The sorted list is built, in place, from right-to-left; that is, the largest value in the list is placed in its final position first, and so on, in the same list. It works by repeatedly comparing two neighboring elements (i.e., in positions *i* and *i*+1). If the two neighboring elements are out of order, they are swapped. The algorithm advances the position *i* and repeats. If, at the end of one iteration of the entire list (also called a **pass**) any swaps were made, the process is repeated. If no swaps were made, it means the list is sorted, and the process terminates.

The following is an example of the bubble sort on the list [7 9 3 5 1], with the underlined elements showing where the comparisons are made in each pass and red indicating the sorted portion of the list:

**Pass 1**

| List | Comparison | Action |
|---|---|---|
| 7 9 3 5 1 | 7 < 9 | no swap |
| 7 9 3 5 1 | 9 > 3 | swap |
| 7 3 9 5 1 | 9 > 5 | swap |
| 7 3 5 9 1 | 9 > 1 | swap |
| 7 3 5 1 **9** | — | done with this pass |

**Pass 2**

| List | Comparison | Action |
|---|---|---|
| 7 3 5 1 9 | 7 > 3 | swap |
| 3 7 5 1 9 | 7 > 5 | swap |
| 3 5 7 1 9 | 7 > 1 | swap |
| 3 5 1 **7 9** | — | done with this pass |

**Pass 3**

| List | Comparison | Action |
|---|---|---|
| 3 5 1 7 9 | 3 < 5 | no swap |
| 3 5 1 7 9 | 5 > 1 | swap |
| 3 1 **5 7 9** | — | done with this pass |

**Pass 4**

| List | Comparison | Action |
|---|---|---|
| 3 1 5 7 9 | 3 > 1 | swap |
| **1 3 5 7 9** | — | done with the sort |

This sort is called the bubble sort because, during each pass, larger values bubble to the end of the list. Note that the bubble sort required four passes through the list of items. That is, it needed to go through some portion of the list starting at the beginning, compare values, and potentially swap values four times. In general for a list of *n* items, the bubble sort requires *n*-1 passes through the list. Did you notice that, as each pass was made, fewer and fewer elements in the list were compared. In the first pass, for example, four comparisons were made; in the second pass, three comparisons were made; in the third pass, two comparisons were made; and in the final pass, only one comparison was made. If we consider all passes in aggregate, on average about half of the values were compared; therefore, for a list of *n* items, an average of *n*/2 comparisons are made at each pass.

We can now calculate the number of comparisons made using the bubble sort as follows:

$$\text{comparisons} = \text{number of passes} \times \text{average number of comparisons per pass}$$

As stated, for a list of *n* items, *n*-1 passes are required, each of which on average makes *n*/2 comparisons. In total, the number of comparisons made using the bubble sort is then:

$$(n-1) \cdot \frac{n}{2} = \frac{1}{2}n(n-1) = \frac{1}{2}(n^2 - n)$$

For the list above of five items, the number of comparisons is then:

$$\frac{1}{2}(5^2 - 5) = \frac{1}{2}(20) = 10$$

In each pass of the bubble sort on the list in the example above, swaps were made. Let's take a look at an example where the list of items is almost already sorted:

**Pass 1**

| List | Comparison | Action |
|---|---|---|
| 1 2 3 5 4 | 1 < 2 | no swap |
| 1 2 3 5 4 | 2 < 3 | no swap |
| 1 2 3 5 4 | 3 < 5 | no swap |
| 1 2 3 5 4 | 5 > 4 | swap |
| 1 2 3 **4 5** | — | done with this pass |

**Pass 2**

| List | Comparison | Action |
|---|---|---|
| 1 2 3 4 5 | 1 < 2 | no swap |
| 1 2 3 4 5 | 2 < 3 | no swap |
| 1 2 3 4 5 | 3 < 4 | no swap |
| **1 2 3 4 5** | — | done with the sort |

Since no swaps were made in pass 2, then the sort is immediately terminated. Terminating the bubble sort during a pass if no swaps are made is a tweak on the original bubble sort called the **optimized bubble sort**.

The method illustrated on the sort the list [7 9 3 5 1] in the table above is great for showing each comparison and illustrating the bubble sort in detail; however, it is overkill when simply showing how a list is sorted. We can slightly deviate from the method used previously and instead summarize each pass in a single row of the table. The underlined items in the list at each pass represent the unsorted portion of the list:

| Pass | List |
|---|---|
| original list | 7 9 3 5 1 |
| 1 | 7 3 5 1 **9** |
| 2 | 3 5 1 **7 9** |
| 3 | 3 1 **5 7 9** |
| 4 | **1 3 5 7 9** |

Show how the bubble sort works on the list [9 1 2 5 3 7] by completing the table below:

| Pass | List |
|---|---|
| original list | 9 1 2 5 3 7 |
| 1 | |
| 2 | |
| 3 | |
| 4 | |
| 5 | |
