---
title: "Insertion Sort"
---

The insertion sort is the procedure that most people use to arrange a hand of cards. To begin to understand the algorithm, think of the list as having both a sorted portion and an unsorted portion (as we did in the previous sorts). The first item of the list is considered to be a sorted list one item long, with the rest of the list (items 2 through *n*) forming an unsorted portion.

The insertion sort removes the first item from the unsorted portion of the list and marks it as the item to be inserted. It then works its way from the back to the front of the sorted portion of the list, at each step comparing the item to be inserted with the current item. As long as the current item is larger than the item to be inserted, the algorithm continues moving backward through the sorted portion of the list. Eventually it will either reach the beginning of the sorted portion of the list or encounter an item that is less than or equal to the item to be inserted. When that happens the algorithm inserts the item at the current insertion point.

The entire process of selecting the first item from the unsorted portion of the list and scanning backwards through the sorted portion of the list for the insertion point is then repeated. Eventually, the unsorted portion of the list will be empty since all of the items will have been inserted into the sorted portion of the list. When this occurs, the sort is complete.

The following is an example of the insertion sort on the list [7 9 3 5 1] with the underlined elements showing where the comparisons are made in each pass, the bold value indicating the current first item in the unsorted portion of the list, and red indicating the sorted portion of the list:

**Pass 1**

| List | First item | Comparison | Action |
|---|---|---|---|
| 7 9 3 5 1 | 9 | 7 < 9 | — |
| 7 **9** 3 5 1 | — | — | done with this pass; insert 9 |

**Pass 2**

| List | First item | Comparison | Action |
|---|---|---|---|
| 7 9 3 5 1 | 3 | 9 > 3 | slide 9 over |
| 7 3 9 5 1 | 3 | 7 > 3 | slide 7 over |
| **3 7 9** 5 1 | — | — | done with this pass; insert 3 |

**Pass 3**

| List | First item | Comparison | Action |
|---|---|---|---|
| 3 7 9 5 1 | 5 | 9 > 5 | slide 9 over |
| 3 7 5 9 1 | 5 | 7 > 5 | slide 7 over |
| 3 5 7 9 1 | 5 | 3 < 5 | — |
| **3 5 7 9** 1 | — | — | done with this pass; insert 5 |

**Pass 4**

| List | First item | Comparison | Action |
|---|---|---|---|
| 3 5 7 9 1 | 1 | 9 > 1 | slide 9 over |
| 3 5 7 1 9 | 1 | 7 > 1 | slide 7 over |
| 3 5 1 7 9 | 1 | 5 > 1 | slide 5 over |
| 3 1 5 7 9 | 1 | 3 > 1 | slide 3 over |
| **1 3 5 7 9** | — | — | done with the sort; insert 1 |

Again, we can show how the insertion sort works by summarizing each pass in a single row of the table. The underlined items in the list at each pass represent the unsorted portion of the list:

| Pass | List |
|---|---|
| original list | 7 9 3 5 1 |
| 1 | **7 9** 3 5 1 |
| 2 | **3 7 9** 5 1 |
| 3 | **3 5 7 9** 1 |
| 4 | **1 3 5 7 9** |

Show how the insertion sort works on the list [9 1 2 5 3 7] by completing the table below:

| Pass | List |
|---|---|
| original list | 9 1 2 5 3 7 |
| 1 | |
| 2 | |
| 3 | |
| 4 | |
| 5 | |

Note that the insertion sort required four passes through the list of items. For a list of *n* items, the insertion sort requires *n*-1 passes through the list, which is the same as both the bubble sort and the selection sort. However, the number of comparisons made at each pass is not so simple to calculate because it depends on the original state of the list. Sometimes, the first item in the unsorted portion of the list will be greater than everything in the sorted portion of the list, and therefore only require one comparison (to the last value in the sorted portion of the list). At other times, it may actually be the smallest value in the entire list and thus be compared to every value in the sorted portion of the list. Since the number of comparisons made in the insertion sort is not so straightforward, we will need to determine formulas that represent the number of comparisons for the worst case, best case, and average case.

In the **best case**, only a single comparison will be made at each pass (i.e., the first item in the unsorted portion of the list is in its proper place in the list). This will happen, for example, if the list is already sorted. For a list of *n* items, the insertion sort requires *n*-1 passes, and for each pass, one comparison is made in the best case. The total number of comparisons in the best case is then:

$$(n-1) \cdot 1 = n - 1$$

For the list above of five items, the number of comparisons in the best case is then four (5 – 1 = 4). Here is an example on the already sorted list [1 2 3 4 5]:

**Pass 1**

| List | First item | Comparison | Action |
|---|---|---|---|
| 1 2 3 4 5 | 2 | 1 < 2 | — |
| **1 2** 3 4 5 | — | — | done with this pass; insert 2 |

**Pass 2**

| List | First item | Comparison | Action |
|---|---|---|---|
| 1 2 3 4 5 | 3 | 2 < 3 | — |
| **1 2 3** 4 5 | — | — | done with this pass; insert 3 |

**Pass 3**

| List | First item | Comparison | Action |
|---|---|---|---|
| 1 2 3 4 5 | 4 | 3 < 4 | — |
| **1 2 3 4** 5 | — | — | done with this pass; insert 4 |

**Pass 4**

| List | First item | Comparison | Action |
|---|---|---|---|
| 1 2 3 4 5 | 5 | 4 < 5 | — |
| **1 2 3 4 5** | — | — | done with the sort; insert 5 |

In the **worst case**, the first item belongs at the beginning of the sorted portion of the list and therefore is compared to every value in the sorted portion of the list. In the first pass, only one comparison is made; in the second pass, two comparisons are made; and so on. On average, then, *n*/2 comparisons are made per pass. For a list of *n* items, the insertion sort requires *n*-1 passes, and for each pass, an average of *n*/2 comparisons are made in the worst case. The total number of comparisons in the worst case is then:

$$(n-1) \cdot \frac{n}{2} = \frac{1}{2}n(n-1) = \frac{1}{2}(n^2 - n)$$

For a list of five items, the number of comparisons in the worst case is then:

$$\frac{1}{2}(5^2 - 5) = \frac{1}{2}(20) = 10$$

In the first example shown with the list [7 9 3 5 1], the worst case indeed occurred (and 10 comparisons were made). Note that the list is nearly reverse sorted!

For the **average case**, we simply need to calculate the average of the average number of comparisons made in the best and worst cases. In the best case, only one comparison is made per pass; in the worst case, *n*/2 comparisons are made. The average is then *n*/4 comparisons. For a list of *n* items, the insertion sort requires *n*-1 passes, and for each pass, an average of *n*/4 comparisons are made in the average case. The total number of comparisons in the average case is then:

$$(n-1) \cdot \frac{n}{4} = \frac{1}{4}n(n-1) = \frac{1}{4}(n^2 - n)$$

For a list of five items, the number of comparisons in the average case is then:

$$\frac{1}{4}(5^2 - 5) = \frac{1}{4}(20) = 5$$

To summarize, an insertion sort of *n* items always requires exactly *n*-1 passes through the sorted portion of the list. What varies is the number of comparisons that must be performed per pass. The best case requires only one comparison per pass and occurs when attempting to sort a list that is already sorted. The worst case requires an average of *n*/2 comparisons per pass and occurs when the list is already sorted in reverse order. In the average case, only one half of the items in the sorted portion of the list will be examined during each pass before the insertion point is found – giving *n*/4 comparisons per pass.
